version: "3.9"
services:
 database:
  image: mysql:5.6
  restart: always
  container_name: mysql-standalone
  environment:
   MYSQL_DATABASE: 'test'
   MYSQL_USER: 'sa'
   MYSQL_PASSWORD: 'password'
   MYSQL_ROOT_PASSWORD: 'password'
  ports:
   - "1306:3306"
 user-mysql:
  build: .
  image: user-mysql
  restart: always
  container_name: user-mysql
  depends_on:
   - database
  ports:
   - "8089:8089"
  